// The propose page redoes in the browser what CI does in Python.  These tests run both sides on the same input:
//   * a file generated by the page passes the Python validator, with the same fields (and invalid drafts fail both);
//   * kebab, the BibTeX parser, the entry formatter and the citation resolver give identical results.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import * as S from '../../site/static/js/bank-search.js';
import * as P from '../../site/static/js/bank-propose.js';
import * as T from '../../site/static/js/bank-tex.js';

const ROOT = new URL('../../', import.meta.url).pathname;
const TAGS = ROOT + 'site/static/bank/tags.json';
const BIB = ROOT + '../problem-bank/references.bib';

const PY = String.raw`
import json, os, sys, tempfile
sys.path.insert(0, os.getcwd())
from bank import paths, problems as P
from bank.bib import format_entry, parse_bib, parse_bib_entries
from bank.stitch import find_figures, label_refs, resolve_citations, split_body
from bank.tags import load_tags
req = json.load(sys.stdin)
out = {}
out["kebab"] = [P.kebab(t) for t in req.get("kebab", [])]
out["bib"] = [parse_bib_entries(t) for t in req.get("bib", [])]
out["format"] = [format_entry(e) for e in req.get("format", [])]
out["cite"] = [list(resolve_citations(s, sol, bib, lambda *a: None, "0")) for s, sol, bib in req.get("cite", [])]
out["unprintable"] = [P.unprintable(t) for t in req.get("unprintable", [])]
out["mask"] = [P.mask_comments(t) for t in req.get("mask", [])]
out["labels"] = [[label_refs(t)[0], [list(r) for r in label_refs(t)[1]]] for t in req.get("labels", [])]
out["figures"] = [[list(f) for f in find_figures(t)] for t in req.get("figures", [])]
out["dates"] = [P._valid_date(t, allow_partial=True) for t in req.get("dates", [])]
files = []
if req.get("files"):
    tags, keys = load_tags(paths.TAGS_FILE), set(parse_bib(paths.BIB_FILE))
    with tempfile.TemporaryDirectory() as d:
        for name, text in req["files"]:
            path = os.path.join(d, name)
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
            p = P.parse_problem_file(path)
            P.validate(p, tags, keys)
            st, so = split_body(p["body"])
            files.append({"errors": [m for _, m in p["errors"]], "new": p["new"], "title": p["title"], "area": p["area"],
                          "methods": p["methods"], "difficulty": p["difficulty"], "origin": p["origin"], "originDate": p["origin_date"],
                          "originNumber": p["origin_number"], "references": p["references"], "review": p["review"], "history": p["history"],
                          "statement": st, "solution": so, "bibKeys": [k for k, _ in p["bib_entries"]], "label": P.origin_label(p, tags)})
out["files"] = files
print(json.dumps(out, ensure_ascii=False))
`;

function python(req) {
  const r = spawnSync('python3', ['-c', PY], { cwd: ROOT, input: JSON.stringify(req), encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  assert.equal(r.status, 0, r.stderr);
  return JSON.parse(r.stdout);
}

test('kebab: JS == Python (with the transliteration table: ß, æ, ø, œ, ł, Greek letters…)', () => {
  const titles = ["Simon's favourite factoring trick", 'Sudakov & Milojević, 2 planets!', '  Hello   World ', 'Théorème de Fermat’s',
    'Straße über Öl', 'x^2 + y^2 = z^2', 'Ǆemal İstanbul', '1+1=2', '', '!!!', 'Untitled problem',
    'ÆØÅ æøå Œœ', 'Σ-algebras and π', 'µ-law', 'π and e', 'φ and e', 'αβγ', 'Łódź, Đakovo, Þórr', 'ẞ ı ŋ ħ ŧ ĸ ð', 'ϑ ϕ ϖ ϱ ϵ ς', 'Ἀλφα ΆΩ ΣΑΣ',
    Object.keys(P.TRANSLIT).join(' '), Object.keys(P.TRANSLIT).join('').toUpperCase()];
  // the same table must be in bank/problems.py::kebab, or CI refuses the file names the page writes
  assert.deepEqual(titles.map(P.kebab), python({ kebab: titles }).kebab, 'bank/problems.py::kebab must use the same transliteration table');
});

test('BibTeX parser: JS == Python (references.bib and awkward input)', () => {
  const texts = [readFileSync(BIB, 'utf8'),
    '@article{a, title = {Nested {braces} here}, year = 2020, author = "Doe, J. and Roe, R."}',
    'stray text @comment{ignored} @misc{nokey} @book{b, title={Unclosed quote}, note = "never closed}',
    '@ARTICLE{ c , Title={X},\n\n  pages = 1--2 ,}  @string{s = "x"} @preamble{"p"} @@@ @misc{d,title={é ü}}',
    '@misc{e, title}', '@misc{f, = {x}}', '@misc{g, title = }', '', 'no entries at all',
    // whitespace that JS and Python disagree on (JS \\s has U+FEFF, Python's has U+001C-U+001F and U+0085)
    '@misc{k\ufeff, title={a\ufeffb}} @misc{\u001ck\u001d\u001e\u001f, title = {x\u0085y}, year\u001f=\u001f2020\u001f, note = z\ufeff}',
    '@misc\u001f{a, title={t}} @misc\ufeff{b, title={t}} @misc{c,\u0085author = {Doe, Jane\u001fand\u001fRoe, R.}}'];
  const py = python({ bib: texts }).bib;
  texts.forEach((t, i) => assert.deepEqual(T.parseBibEntries(t), py[i], `text ${i}`));
});

test('entry formatter: JS == Python on every entry of references.bib and edge cases', () => {
  const entries = T.parseBibEntries(readFileSync(BIB, 'utf8')).map(([, f]) => f);
  entries.push({ title: 'k' }, { title: 'Springer chapter', doi: '10.1007/978-3-642-15546-8_7' }, { title: 'On a theorem of {Euler}' },
    { title: '{{Protected}}' }, { title: '{A} and {B}' }, { title: '}{' }, { author: 'A and B and C', title: '{T}', journal: 'J', volume: '1', number: '2', year: '3', pages: '4--5' },
    { eprint: '1234.5678', archiveprefix: 'arXiv', url: 'https://x.y', note: 'see arXiv' }, { publisher: 'P', howpublished: 'H', note: 'N' }, {});
  assert.ok(entries.length >= 9);
  assert.deepEqual(entries.map(T.formatEntry), python({ format: entries }).format);
});

test('printable characters of titles / origin numbers: JS == Python on every code point up to U+33FF', () => {
  const chunks = [];
  for (let c = 0; c < 0x3400; c += 256) chunks.push(Array.from({ length: 256 }, (_, i) => String.fromCodePoint(c + i)).join(''));
  chunks.push('√2 ≤ π^2 😀 Ωmega φ – … € ‰ ′');
  assert.deepEqual(chunks.map(t => P.unprintable(t)), python({ unprintable: chunks }).unprintable);
});

test('citation resolver: JS == Python', () => {
  const bib = Object.fromEntries(T.parseBibEntries(readFileSync(BIB, 'utf8')));
  const cases = [
    ['See \\cite{solomon1967Hurwitz} and \\parencite[p.~3]{sato1972algebraic, solomon1967Hurwitz}.', 'Also \\textcite[see][12]{missing,sato1972algebraic}.\n\\printbibliography\nEnd.', bib],
    ['No citations.', null, bib],
    ['\\cite[]{a}\n  \\nocite{*}\n\\cite{b}', 'Only \\cite{c} here.  ', {}],
    ['Text', 'Sol \\cite{x}', { x: { title: 'X' } }],
    ['\\cite{a\u001f, \ufeffb} \\cite[\u0085p. 2\u001f]{a}\u001f\u0085', null, { a: { author: 'X\u0085and\u0085Y', title: 'A' } }],
    // the optional notes are bounded to 300 characters on both sides (many unclosed \cite[ would be quadratic)
    ['\\cite[' + 'n'.repeat(300) + ']{a} \\cite[' + 'n'.repeat(301) + ']{b} \\cite[x \\cite[y]{c}', null, {}],
    // \cite* and the spaces TeX allows; \citeauthor & co. are not resolved (the validator refuses them)
    ['\\cite*{a} \\cite [p.~3] {b} \\parencite\n[see][12]\n{a,c} \\citeauthor{a} \\cite*[x]{d}', 'Sol \\textcite *{e} \\footcite{a}', { a: { title: 'A' } }],
  ];
  const py = python({ cite: cases }).cite;
  cases.forEach(([st, so, b], i) => {
    const js = T.resolveCitations(st, so, b);
    assert.deepEqual([js.statement, js.solution, js.count], py[i], `case ${i}`);
  });
});

test('comments, labels, figures and dates: JS == Python', () => {
  const texts = ['a % c\n50\\% b %x\n\\\\% y\n%z', '\\\\\\% odd, \\\\\\\\% even\n%% two\n\\%%', '', 'no comment', '%\n%\n', 'x%',
    '% \\begin{tikzpicture}\n\\begin{tikzpicture}\\draw (0,0) -- (1,1); % \\end{tikzpicture}\n\\end{tikzpicture} \\begin{tikzcd}A\\end{tikzcd}',
    '\\label{a} \\ref {a,b} \\labelcref[lemma]{c} \\crefrange{x}{y} \\Crefrange * {x} {z} \\hyperref [z, w]{t} \\label[t] {d} \\eqref*{e}\n\\hypertarget{h}{H} \\hyperlink{h}{H} \\label{a} \\cref{ a ,\u001fb}'];
  const py = python({ mask: texts, labels: texts, figures: texts, dates: [] });
  assert.deepEqual(texts.map(T.maskComments), py.mask);
  assert.deepEqual(texts.map(t => { const r = T.labelRefs(t); return [{ ...r.targets }, r.refs]; }), py.labels);
  assert.deepEqual(texts.map(T.findFigures), py.figures);
  const dates = ['1989', '1989-12', '1989-12-02', '2024-02-29', '2023-02-29', '0000', '0000-01', '0001', '0050-01-31', '0099-12-31', '9999-12-31',
    '1989-00', '1989-13', '1989-1-2', '89', '1989/12', '１９８９', '1989-12-02T00', ' 1989', '1989-12-32', '2000-02-30'];
  assert.deepEqual(dates.map(P.validDate), python({ dates }).dates);
});

test('files made by the page pass the Python validator with the same fields; invalid drafts fail both', (t) => {
  if (!existsSync(TAGS)) { t.skip('site/static/bank/tags.json not built'); return; }
  const cat = S.buildCatalogue(JSON.parse(readFileSync(TAGS, 'utf8')));
  const bibKeys = T.parseBibEntries(readFileSync(BIB, 'utf8')).map(([k]) => k);
  const base = { ...P.emptyDraft(), statement: 'Prove that $1+1=2$.', area: ['primes'] };
  const good = [
    base,
    { ...base, title: 'Sum of two cubes', statement: 'Show \\cite{solomon1967Hurwitz} and \\cite{own}:\n\\begin{tikzpicture}\n\\draw (0,0) -- (1,1);\n\\end{tikzpicture}\n50\\% done.',
      solution: '\n\nBy induction \\cite[p.~2]{own}.\n\n  \n', area: ['primes', 'divisibility'], methods: ['induction', 'pigeonhole'], difficulty: 'medium',
      origin: 'putnam', originDate: '1989-12-02', originNumber: 'A3', references: 'https://example.org/a\nKalva, Putnam 1989', bibtex: '@article{own,\n  author = {Doe, Jane},\n  title = {Own},\n  year = {2020},\n}' },
    { ...base, title: 'Théorème de Fermat’s', originDate: '2001' },
    { ...base, title: '  spaced    out  title ', statement: '  \n% a comment line first\n\\[ x \\]\n' },
    { ...base, title: 'Euler φ sums', originNumber: 'Day 2, Problem 6', statement: 'See \\cite{b1}.', bibtex: '@misc{b1, title = {On a theorem of {Euler}}, doi = {10.1/a_b}}' },
    { ...base, title: 'Straße, Œuvre, αβγ', statement: 'See \\cite{k}.', bibtex: '@misc{k\u001f, title={x}}' },
    { ...base, originDate: '0050-01-31', statement: 'See \\cite*{own} and \\cite [p.~3] {own}.\n% \\begin{tikzpicture}\n\\begin {align*} x \\end{align*}',
      bibtex: '@misc{own, title = {Own}}' },
    { ...base, statement: 'Show (\\ref{eq}).\\begin{equation}\\label{eq} x \\end{equation}', solution: 'By \\eqref{eq} and \\cref{l}. \\label{l}' },
  ];
  const bad = [
    { ...base, title: 'A & B' }, { ...base, title: 'one two three four five six seven' }, { ...base, originDate: '1989-13' },
    { ...base, statement: 'See \\cite{nowhere}.' }, { ...base, bibtex: '@misc{a, title={x}}\n@misc{a, title={y}}' },
    { ...base, statement: '\\tikz \\draw (0,0) -- (1,1);' }, { ...base, solution: '\\usepackage{xcolor}' }, { ...base, area: [] },
    { ...base, bibtex: 'nothing here' }, { ...base, statement: 'x\n\\end{document}' },
    { ...base, title: '√2 is irrational' }, { ...base, origin: 'putnam', originNumber: 'A^2' }, { ...base, statement: 'A \\end {problem}\\end {document}' },
    { ...base, statement: 'A\n\\bibliography{references}' }, { ...base, statement: 'x \\begin {problem} y' },
    { ...base, statement: 'See \\cite{b1}.', bibtex: '@misc{b1, title = {Why not \\usepackage{tikz}}}' },
    { ...base, statement: 'See \\cite{b1}.', bibtex: '@misc{b1, title = {Drawing with \\tikz here}}' },
    { ...base, statement: 'See \\cite{k}.', bibtex: '@misc{k\ufeff, title={x}}' },
    // rules added for the website's one-document PDFs and CI's runner (bank/problems.py::UNSAFE_TEX and co.)
    { ...base, statement: '\\def\\x{1} $\\x$' }, { ...base, solution: 'x \\let\\a\\b' }, { ...base, statement: 'x % \\gdef\\y{2}' },
    { ...base, statement: 'x \\endinput' }, { ...base, statement: '$x^^41$' }, { ...base, statement: '\\begin align x' },
    { ...base, statement: '\\newtheorem{claim}{Claim}' }, { ...base, statement: '\\input{/etc/passwd}' }, { ...base, solution: '\\includegraphics{a.png}' },
    { ...base, statement: 'Today is \\today.' }, { ...base, statement: '\\pdfuniformdeviate 10' }, { ...base, statement: '\\bankproblem{2}{X}{}{}' },
    { ...base, statement: '\\begin{problemreferences}\\refitem{1} x\\end{problemreferences}' }, { ...base, statement: '\\citeauthor{solomon1967Hurwitz}' },
    { ...base, statement: 'See \\cite{b1}.', bibtex: '@misc{b1, title = {A \\def\\z{} title}}' }, { ...base, bibtex: '@misc{b1, note = {\\citeyear{x}}}' },
    { ...base, statement: 'By Lemma \\ref{lem}.', solution: '\\begin{lemma}\\label{lem} x \\end{lemma}' },
    { ...base, originDate: '0000' }, { ...base, area: ['primes', 'primes'] },
  ];
  const all = [...good, ...bad];
  const py = python({ files: all.map(d => [P.fileName(d), P.problemFile(d)]) }).files;
  good.forEach((d, i) => {
    const r = py[i];
    assert.deepEqual(P.validateDraft(d, cat, bibKeys), [], `JS accepts good draft ${i}`);
    assert.deepEqual(r.errors, [], `Python accepts good draft ${i}`);
    assert.equal(r.new, true);
    assert.deepEqual([r.title, r.area, r.methods, r.difficulty, r.origin, r.originDate, r.originNumber, r.review, r.history],
      [P.effectiveTitle(d), d.area, d.methods, d.difficulty, d.origin, d.originDate.trim(), d.originNumber.trim(), 'none', 'none']);
    assert.equal(r.label, P.originLabel(cat, d.origin, d.originDate, d.originNumber));
    assert.equal(r.statement, d.statement.replace(/^(?:[ \t]*\n)+/, '').replace(/\s+$/, ''));
    assert.equal(r.solution, d.solution.trim() ? d.solution.replace(/^(?:[ \t]*\n)+/, '').replace(/\s+$/, '') : null);
    assert.deepEqual(r.bibKeys, T.parseBibEntries(d.bibtex).map(([k]) => k));
  });
  assert.equal(py[1].references, 'https://example.org/a; Kalva, Putnam 1989');
  bad.forEach((d, i) => {
    const r = py[good.length + i];
    assert.notDeepEqual(P.validateDraft(d, cat, bibKeys), [], `JS rejects bad draft ${i}`);
    assert.notDeepEqual(r.errors, [], `Python rejects bad draft ${i}: ${P.problemFile(d)}`);
  });
});
